const HOTEL_DATA = [
  {"city":"Tikamgarh","tier":"Tier-4 Tourism","name":"Hotel Shiv Residency","priceRange":"0-1000","price":700,"stars":"Budget/OYO","locationType":"Town Centre / Market","area":"Nagar Palika Chowk","distRailway":1.2,"distAirport":185,"distBus":0.4,"reviews":84,"rating":3.8,"familyScore":6,"soloScore":5,"activityScore":7},
  {"city":"Tikamgarh","tier":"Tier-4 Tourism","name":"Hotel Palace View","priceRange":"1000-3000","price":1800,"stars":"2-Star","locationType":"Near Fort Road","area":"Gandhi Chowk","distRailway":1.8,"distAirport":185,"distBus":0.9,"reviews":210,"rating":4.0,"familyScore":7,"soloScore":6,"activityScore":8},
  {"city":"Tikamgarh","tier":"Tier-4 Tourism","name":"The Orchid Retreat","priceRange":"3000-7000","price":4500,"stars":"3-Star Boutique","locationType":"Heritage Zone","area":"Fort Road, Old City","distRailway":2.1,"distAirport":185,"distBus":1.4,"reviews":310,"rating":4.2,"familyScore":8,"soloScore":6,"activityScore":8},
  {"city":"Tikamgarh","tier":"Tier-4 Tourism","name":"Raja's Grand","priceRange":"7000+","price":8500,"stars":"Heritage Resort","locationType":"Outskirts / Scenic","area":"Bypass Road","distRailway":3.5,"distAirport":185,"distBus":3.2,"reviews":95,"rating":4.4,"familyScore":9,"soloScore":7,"activityScore":9},
  {"city":"Chanderi","tier":"Tier-4 No Tourism","name":"Hotel Chanderi Palace","priceRange":"0-1000","price":850,"stars":"Budget","locationType":"Market Area","area":"Main Bazaar","distRailway":2.0,"distAirport":210,"distBus":0.3,"reviews":60,"rating":3.6,"familyScore":5,"soloScore":5,"activityScore":6},
  {"city":"Chanderi","tier":"Tier-4 No Tourism","name":"Hotel Bundelkhand Inn","priceRange":"1000-3000","price":2000,"stars":"2-Star","locationType":"Near Bus Stand","area":"Bus Stand Road","distRailway":2.5,"distAirport":210,"distBus":0.2,"reviews":135,"rating":3.9,"familyScore":7,"soloScore":6,"activityScore":6},
  {"city":"Chanderi","tier":"Tier-4 No Tourism","name":"Chanderi Heritage Haveli","priceRange":"3000-7000","price":5200,"stars":"Boutique Heritage","locationType":"Heritage Core","area":"Shehzadi ka Roza Road","distRailway":2.8,"distAirport":210,"distBus":1.6,"reviews":240,"rating":4.3,"familyScore":8,"soloScore":7,"activityScore":9},
  {"city":"Chanderi","tier":"Tier-4 No Tourism","name":"Weaver's Retreat","priceRange":"7000+","price":9000,"stars":"Luxury Boutique","locationType":"Silk Weaving Village","area":"Village Outskirts","distRailway":4.0,"distAirport":210,"distBus":3.5,"reviews":72,"rating":4.5,"familyScore":8,"soloScore":7,"activityScore":9},
  {"city":"Ayodhya","tier":"Pilgrimage","name":"Hotel Ram Darbar","priceRange":"0-1000","price":900,"stars":"Budget","locationType":"Near Ghats","area":"Saryu Ghat Road","distRailway":3.5,"distAirport":16,"distBus":0.8,"reviews":520,"rating":3.7,"familyScore":7,"soloScore":6,"activityScore":9, "vegAndNoAlcohol": true},
  {"city":"Ayodhya","tier":"Pilgrimage","name":"Treebo Ram Niwas","priceRange":"1000-3000","price":2200,"stars":"2-Star","locationType":"Ram Mandir Vicinity","area":"Naya Ghat","distRailway":3.8,"distAirport":16,"distBus":1.1,"reviews":870,"rating":4.1,"familyScore":8,"soloScore":6,"activityScore":9, "vegAndNoAlcohol": true},
  {"city":"Ayodhya","tier":"Pilgrimage","name":"Hotel Krishna Palace","priceRange":"3000-7000","price":4800,"stars":"3-Star","locationType":"Civil Lines / Mid-City","area":"Civil Lines","distRailway":2.5,"distAirport":8,"distBus":1.5,"reviews":1240,"rating":4.3,"familyScore":8,"soloScore":7,"activityScore":8, "vegAndNoAlcohol": true, "onSiteDining": true},
  {"city":"Ayodhya","tier":"Pilgrimage","name":"Saket Suites","priceRange":"7000+","price":12000,"stars":"4-Star","locationType":"Upscale / Temple Corridor","area":"Ram Path, VIP Zone","distRailway":4.2,"distAirport":6,"distBus":2.8,"reviews":680,"rating":4.6,"familyScore":9,"soloScore":7,"activityScore":10, "vegAndNoAlcohol": true, "onSiteDining": true},
  {"city":"Manali","tier":"Hill Station","name":"Snow Valley Hostel & Inn","priceRange":"0-1000","price":950,"stars":"Budget / Hostel","locationType":"Old Manali Village","area":"Old Manali Road","distRailway":1.2,"distAirport":50,"distBus":1.4,"reviews":1100,"rating":4.0,"familyScore":5,"soloScore":9,"activityScore":9,"scenicOrNature":true},
  {"city":"Manali","tier":"Hill Station","name":"Hotel Beas Residency","priceRange":"1000-3000","price":2500,"stars":"2-Star","locationType":"Mall Road Area","area":"Mall Road, Manali","distRailway":0.8,"distAirport":50,"distBus":0.5,"reviews":2340,"rating":4.2,"familyScore":7,"soloScore":7,"activityScore":8,"scenicOrNature":true, "onSiteDining": true},
  {"city":"Manali","tier":"Hill Station","name":"Solang Valley Resort","priceRange":"3000-7000","price":5500,"stars":"3-Star Resort","locationType":"Near Activity Zone","area":"Solang Valley","distRailway":8.0,"distAirport":52,"distBus":9.0,"reviews":1890,"rating":4.4,"familyScore":8,"soloScore":7,"activityScore":10,"scenicOrNature":true, "onSiteDining": true},
  {"city":"Manali","tier":"Hill Station","name":"The Himalayan (CGH Earth)","priceRange":"7000+","price":14000,"stars":"5-Star Resort","locationType":"Riverside Luxury","area":"Manali-Naggar Road","distRailway":3.5,"distAirport":51,"distBus":3.0,"reviews":3200,"rating":4.7,"familyScore":9,"soloScore":8,"activityScore":10,"scenicOrNature":true, "onSiteDining": true},
  {"city":"Jim Corbett","tier":"National Park","name":"Corbett Nestling Hostel","priceRange":"0-1000","price":900,"stars":"Budget / Hostel","locationType":"Gate Area / Village","area":"Ramnagar Town","distRailway":0.5,"distAirport":75,"distBus":0.3,"reviews":420,"rating":3.9,"familyScore":5,"soloScore":8,"activityScore":7, "safariPermit": true},
  {"city":"Jim Corbett","tier":"National Park","name":"Hotel Corbett Inn","priceRange":"1000-3000","price":2200,"stars":"2-Star","locationType":"Near Park Entry Gate","area":"Dhikuli, NH-121","distRailway":6.0,"distAirport":72,"distBus":5.5,"reviews":980,"rating":4.1,"familyScore":7,"soloScore":6,"activityScore":9, "safariPermit": true, "onSiteDining": true},
  {"city":"Jim Corbett","tier":"National Park","name":"Corbett Riverside Resort","priceRange":"3000-7000","price":5800,"stars":"3-Star Resort","locationType":"Jungle Edge / Riverside","area":"Corbett Buffer Zone","distRailway":8.0,"distAirport":75,"distBus":7.5,"reviews":1540,"rating":4.4,"familyScore":8,"soloScore":7,"activityScore":10, "safariPermit": true, "scenicOrNature":true, "onSiteDining": true},
  {"city":"Jim Corbett","tier":"National Park","name":"Jim's Jungle Retreat","priceRange":"7000+","price":15000,"stars":"Luxury Eco-Resort","locationType":"Deep Jungle / Eco Zone","area":"Corbett Tiger Reserve","distRailway":10.0,"distAirport":78,"distBus":9.0,"reviews":2100,"rating":4.8,"familyScore":9,"soloScore":8,"activityScore":10, "safariPermit": true, "scenicOrNature":true, "onSiteDining": true}
];

// Enriching the original data lightly to map specific questions logic.
// e.g. "vegAndNoAlcohol": true added to Ayodhya properties manually for demonstration,
// "scenicOrNature": true added to Manali/Corbett resorts,
// "safariPermit": true added to Corbett resorts.
// "onSiteDining": true added to 3+ star properties.

const CITIES = ["Tikamgarh", "Chanderi", "Ayodhya", "Manali", "Jim Corbett"];
